import pytest
from target_code import *

json
{
  "test_code": [
    "from datetime import datetime, timezone",
    "from unittest.mock import patch",
    "# Fixture to reset the state before each test",
    "@pytest.fixture(autouse=True)",
    "def reset_global_state():",
    "    target_code.reset_demo_state()",
    "# Fixtures to corrupt global state for pytest.raises tests",
    "@pytest.fixture",
    "def corrupt_customers_dict():",
    "    original_customers = target_code._CUSTOMERS",
    "    target_code._CUSTOMERS = None",
    "    yield",
    "    target_code._CUSTOMERS = original_customers",
    "@pytest.fixture",
    "def corrupt_inventory_dict():",
    "    original_inventory = target_code._INVENTORY",
    "    target_code._INVENTORY = None",
    "    yield",
    "    target_code._INVENTORY = original_inventory",
    "@pytest.fixture",
    "def corrupt_carts_dict():",
    "    original_carts = target_code._CARTS",
    "    target_code._CARTS = None",
    "    yield",
    "    target_code._CARTS = original_carts",
    "@pytest.fixture",
    "def corrupt_orders_dict():",
    "    original_orders = target_code._ORDERS",
    "    target_code._ORDERS = None",
    "    yield",
    "    target_code._ORDERS = original_orders",
    "# Helper functions tests",
    "# Note: For _to_int, _to_price, _to_text, and _utc_now, the `except Exception` blocks or inherent robustness",
    "# mean they are designed to return default values or robust results rather than raise exceptions for invalid inputs.",
    "# Their \"failure cases\" are therefore tested by asserting these default/fallback behaviors.",
    "def test_to_int_normal_positive_string():",
    "    assert target_code._to_int(\"123\", 1) == 123",
    "def test_to_int_normal_integer():",
    "    assert target_code._to_int(789, 1) == 789",
    "def test_to_int_edge_float_string():",
    "    assert target_code._to_int(\"123.45\", 1) == 123",
    "def test_to_int_edge_non_numeric_string():",
    "    assert target_code._to_int(\"abc\", 99) == 99",
    "def test_to_int_edge_none_value():",
    "    assert target_code._to_int(None, 50) == 50",
    "def test_to_int_failure_returns_default_on_conversion_error():",
    "    # This function is designed to catch all exceptions and return default.",
    "    # Its failure case is returning the default value.",
    "    assert target_code._to_int(\"not_an_int\", 10) == 10",
    "    assert target_code._to_int([], 20) == 20",
    "def test_to_price_normal_positive_float_string_returns_default():",
    "    # If `result > 0`, it returns the default value.",
    "    assert target_code._to_price(\"50.0\", 200.0) == 200.0",
    "    assert target_code._to_price(\"50.0\") == 100.0  # Uses function's default default",
    "def test_to_price_normal_negative_float_string_returns_value():",
    "    assert target_code._to_price(\"-10.0\", 200.0) == -10.0",
    "def test_to_price_normal_zero_float_string_returns_value():",
    "    assert target_code._to_price(\"0.0\", 200.0) == 0.0",
    "def test_to_price_edge_non_numeric_string_returns_default():",
    "    assert target_code._to_price(\"xyz\", 150.0) == 150.0",
    "def test_to_price_edge_none_value_returns_default():",
    "    assert target_code._to_price(None, 250.0) == 250.0",
    "def test_to_price_failure_returns_default_on_conversion_error():",
    "    # This function is designed to catch all exceptions and return default.",
    "    # Its failure case is returning the default value.",
    "    assert target_code._to_price(\"bad_price\", 50.0) == 50.0",
    "    assert target_code._to_price({}, 60.0) == 60.0",
    "def test_to_text_normal_string():",
    "    assert target_code._to_text(\"  hello world  \", \"default\") == \"hello world\"",
    "def test_to_text_normal_int():",
    "    assert target_code._to_text(123, \"default\") == \"123\"",
    "def test_to_text_edge_empty_string():",
    "    assert target_code._to_text(\"   \", \"default\") == \"default\"",
    "def test_to_text_edge_none_value():",
    "    assert target_code._to_text(None, \"default\") == \"None\"",
    "def test_to_text_failure_empty_string_after_strip_returns_default():",
    "    # This is the \"failure\" mode for _to_text, returning default when stripped value is empty.",
    "    assert target_code._to_text(\"   \", \"fallback\") == \"fallback\"",
    "@patch('target_code.datetime')",
    "def test_utc_now_normal_format(mock_datetime):",
    "    mock_now = datetime(2023, 1, 1, 10, 30, 0, 0, tzinfo=timezone.utc)",
    "    mock_datetime.now.return_value = mock_now",
    "    mock_datetime.timezone = timezone",
    "    assert target_code._utc_now() == \"2023-01-01T10:30:00+00:00\"",
    "def test_utc_now_edge_no_inputs():",
    "    # No direct inputs, so edge case focuses on output type consistency.",
    "    assert isinstance(target_code._utc_now(), str)",
    "def test_utc_now_failure_always_returns_string_not_raises():",
    "    # This function is not designed to raise exceptions. Its \"failure\" is if it didn't return a string,",
    "    # but Python's `datetime.isoformat()` is robust.",
    "    assert isinstance(target_code._utc_now(), str)",
    "# Public functions tests",
    "def test_reset_demo_state_normal():",
    "    # Pre-populate some state to ensure it gets cleared",
    "    target_code._CUSTOMERS[1] = {\"name\": \"Test\"}",
    "    target_code._INVENTORY[1] = {\"name\": \"Test Product\"}",
    "    target_code._NEXT_ORDER_ID = 10",
    "    result = target_code.reset_demo_state()",
    "    assert result[\"customers\"] == 0",
    "    assert result[\"products\"] == 0",
    "    assert result[\"orders\"] == 0",
    "    assert isinstance(result[\"timestamp_utc\"], str)",
    "    assert not target_code._CUSTOMERS",
    "    assert not target_code._INVENTORY",
    "    assert not target_code._CARTS",
    "    assert not target_code._ORDERS",
    "    assert target_code._NEXT_ORDER_ID == 1",
    "def test_reset_demo_state_edge_empty_state_remains_empty():",
    "    # State is already empty due to autouse fixture setup",
    "    result = target_code.reset_demo_state()",
    "    assert result[\"customers\"] == 0",
    "    assert result[\"products\"] == 0",
    "def test_reset_demo_state_failure_corrupt_customers_dict_raises(corrupt_customers_dict):",
    "    # Corrupting a global variable that the function tries to clear",
    "    with pytest.raises(AttributeError):",
    "        target_code.reset_demo_state()",
    "def test_initialize_store_normal_no_seed():",
    "    result = target_code.initialize_store()",
    "    assert result[\"products\"] == 3",
    "    assert result[\"product_ids\"] == [1, 2, 3]",
    "    assert not result[\"seeded\"]",
    "    assert target_code._INVENTORY[1][\"name\"] == \"Starter Plan\"",
    "    assert target_code._INVENTORY[1][\"price\"] == 99.0",
    "    assert target_code._INVENTORY[1][\"stock\"] == 50",
    "def test_initialize_store_normal_with_valid_seed():",
    "    seed = [",
    "        {\"product_id\": 4, \"name\": \"Premium\", \"price\": 299.0, \"stock\": 15},",
    "        {\"product_id\": \"5\", \"name\": \"Basic\", \"price\": \"49.0\", \"stock\": \"100\"},",
    "    ]",
    "    result = target_code.initialize_store(seed)",
    "    assert result[\"products\"] == 5",
    "    assert result[\"product_ids\"] == [1, 2, 3, 4, 5]",
    "    assert result[\"seeded\"]",
    "    assert target_code._INVENTORY[4][\"name\"] == \"Premium\"",
    "    assert target_code._INVENTORY[4][\"price\"] == 299.0",
    "    assert target_code._INVENTORY[4][\"stock\"] == 15",
    "    assert target_code._INVENTORY[5][\"name\"] == \"Basic\"",
    "    assert target_code._INVENTORY[5][\"price\"] == 49.0",
    "    assert target_code._INVENTORY[5][\"stock\"] == 100",
    "def test_initialize_store_edge_seed_with_invalid_items():",
    "    seed = [",
    "        {\"product_id\": 6, \"name\": \"Pro\", \"price\": 199.0, \"stock\": 25},",
    "        \"not a dict\",  # Ignored",
    "        {\"product_id\": -7, \"name\": \"Invalid ID\", \"price\": 10.0, \"stock\": 5},  # Ignored because pid <= 0",
    "        {\"product_id\": 8, \"name\": \"Zero Stock\", \"price\": 5.0, \"stock\": -10},  # Stock becomes 0",
    "        {\"product_id\": 9, \"price\": 10.0, \"stock\": 10},  # No name, uses default",
    "        {\"product_id\": 10, \"name\": \"No Price\", \"stock\": 10},  # No price, uses default",
    "    ]",
    "    result = target_code.initialize_store(seed)",
    "    assert result[\"products\"] == 7",
    "    assert 6 in target_code._INVENTORY",
    "    assert 7 not in target_code._INVENTORY",
    "    assert target_code._INVENTORY[8][\"stock\"] == 0",
    "    assert target_code._INVENTORY[9][\"name\"] == \"Product-9\"",
    "    assert target_code._INVENTORY[10][\"price\"] == 100.0",
    "def test_initialize_store_failure_corrupt_inventory_dict_raises(corrupt_inventory_dict):",
    "    # Corrupting _INVENTORY to make method calls fail",
    "    with pytest.raises(AttributeError):",
    "        target_code.initialize_store()",
    "def test_register_customer_normal_new_customer():",
    "    result = target_code.register_customer(101, \"Alice Smith\")",
    "    assert result[\"customer_id\"] == 101",
    "    assert result[\"name\"] == \"Alice Smith\"",
    "    assert \"created_at\" in result",
    "    assert result[\"is_active\"] is True",
    "    assert 101 in target_code._CUSTOMERS",
    "    assert 101 in target_code._CARTS",
    "    assert target_code._CUSTOMERS[101][\"name\"] == \"Alice Smith\"",
    "def test_register_customer_normal_auto_id_generation():",
    "    target_code.register_customer(1, \"Existing Customer\")",
    "    result = target_code.register_customer(0, \"Bob Johnson\")",
    "    assert result[\"customer_id\"] == 2",
    "    assert result[\"name\"] == \"Bob Johnson\"",
    "    assert 2 in target_code._CUSTOMERS",
    "    assert 2 in target_code._CARTS",
    "def test_register_customer_edge_update_existing_customer():",
    "    target_code.register_customer(101, \"Alice Old Name\")",
    "    result = target_code.register_customer(101, \"Alice New Name\")",
    "    assert result[\"customer_id\"] == 101",
    "    assert result[\"name\"] == \"Alice New Name\"",
    "    assert target_code._CUSTOMERS[101][\"name\"] == \"Alice New Name\"",
    "    assert target_code._CARTS[101] == {}",
    "def test_register_customer_edge_invalid_customer_id():",
    "    result = target_code.register_customer(\"invalid\", \"Charlie\")",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"name\"] == \"Charlie\"",
    "def test_register_customer_edge_invalid_name():",
    "    result = target_code.register_customer(102, None)",
    "    assert result[\"customer_id\"] == 102",
    "    assert result[\"name\"] == \"Customer-102\"",
    "def test_register_customer_failure_corrupt_customers_dict_raises(corrupt_customers_dict):",
    "    # Corrupting _CUSTOMERS to make method calls fail",
    "    with pytest.raises(AttributeError):",
    "        target_code.register_customer(1, \"Alice\")",
    "def test_upsert_inventory_normal_add_to_existing():",
    "    target_code.initialize_store()",
    "    result = target_code.upsert_inventory(1, 10)",
    "    assert result[\"product_id\"] == 1",
    "    assert result[\"stock\"] == 60",
    "    assert result[\"name\"] == \"Starter Plan\"",
    "def test_upsert_inventory_normal_create_new_product():",
    "    result = target_code.upsert_inventory(10, 50)",
    "    assert result[\"product_id\"] == 10",
    "    assert result[\"stock\"] == 50",
    "    assert result[\"name\"] == \"Product-10\"",
    "    assert result[\"price\"] == 100.0",
    "def test_upsert_inventory_edge_invalid_product_id():",
    "    result = target_code.upsert_inventory(\"invalid\", 20)",
    "    assert result[\"product_id\"] == 1",
    "    assert result[\"name\"] == \"Product-1\"",
    "    assert result[\"stock\"] == 20",
    "def test_upsert_inventory_edge_invalid_quantity():",
    "    target_code.initialize_store()",
    "    result = target_code.upsert_inventory(1, \"invalid\")",
    "    assert result[\"product_id\"] == 1",
    "    assert result[\"stock\"] == 50",
    "def test_upsert_inventory_failure_corrupt_inventory_dict_raises(corrupt_inventory_dict):",
    "    # Corrupting _INVENTORY to make method calls fail",
    "    with pytest.raises(AttributeError):",
    "        target_code.upsert_inventory(1, 10)",
    "def test_add_to_cart_normal_add_new_item():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(101, 10)",
    "    result = target_code.add_to_cart(1, 101, 5)",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"product_id\"] == 101",
    "    assert result[\"accepted_quantity\"] == 5",
    "    assert result[\"cart_size\"] == 5",
    "    assert target_code._CARTS[1][101] == 5",
    "def test_add_to_cart_normal_add_to_existing_item():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(101, 10)",
    "    target_code.add_to_cart(1, 101, 3)",
    "    result = target_code.add_to_cart(1, 101, 2)",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"product_id\"] == 101",
    "    assert result[\"accepted_quantity\"] == 2",
    "    assert result[\"cart_size\"] == 5",
    "    assert target_code._CARTS[1][101] == 5",
    "def test_add_to_cart_edge_implicit_customer_and_product_creation():",
    "    # Customer 1 and Product 102 don't exist initially",
    "    result = target_code.add_to_cart(1, 102, 5)",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"product_id\"] == 102",
    "    assert result[\"accepted_quantity\"] == 5",
    "    assert 1 in target_code._CUSTOMERS",
    "    assert 102 in target_code._INVENTORY",
    "    assert target_code._INVENTORY[102][\"stock\"] >= 5",
    "def test_add_to_cart_edge_quantity_exceeds_stock():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(101, 5)",
    "    result = target_code.add_to_cart(1, 101, 10)",
    "    assert result[\"accepted_quantity\"] == 5",
    "    assert result[\"cart_size\"] == 5",
    "    assert target_code._CARTS[1][101] == 5",
    "def test_add_to_cart_edge_zero_or_negative_quantity():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(101, 10)",
    "    result = target_code.add_to_cart(1, 101, 0)",
    "    assert result[\"accepted_quantity\"] == 1",
    "    assert result[\"cart_size\"] == 1",
    "    assert target_code._CARTS[1][101] == 1",
    "def test_add_to_cart_failure_corrupt_carts_dict_raises(corrupt_carts_dict):",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(1, 10)",
    "    with pytest.raises(AttributeError):",
    "        target_code.add_to_cart(1, 1, 5)",
    "def test_create_order_normal_from_populated_cart():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 100)",
    "    target_code.upsert_inventory(20, 50)",
    "    target_code.add_to_cart(1, 10, 2)",
    "    target_code.add_to_cart(1, 20, 1)",
    "    result = target_code.create_order(1, 10.50)",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"status\"] == \"confirmed\"",
    "    assert result[\"subtotal\"] == 400.0",
    "    assert result[\"shipping_fee\"] == 10.50",
    "    assert result[\"total\"] == 410.50",
    "    assert len(result[\"lines\"]) == 2",
    "    assert target_code._INVENTORY[10][\"stock\"] == 98",
    "    assert target_code._INVENTORY[20][\"stock\"] == 49",
    "    assert target_code._CARTS[1] == {}",
    "def test_create_order_normal_empty_cart():",
    "    target_code.register_customer(1, \"Alice\")",
    "    result = target_code.create_order(1, 5.0)",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"customer_id\"] == 1",
    "    assert result[\"status\"] == \"empty\"",
    "    assert result[\"subtotal\"] == 0.0",
    "    assert result[\"shipping_fee\"] == 5.0",
    "    assert result[\"total\"] == 5.0",
    "    assert not result[\"lines\"]",
    "def test_create_order_edge_non_existent_customer_id():",
    "    # Will implicitly register the customer and create an empty order",
    "    result = target_code.create_order(99, 0)",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"customer_id\"] == 99",
    "    assert result[\"status\"] == \"empty\"",
    "    assert 99 in target_code._CUSTOMERS",
    "def test_create_order_edge_insufficient_stock_for_some_items():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 5)",
    "    target_code.upsert_inventory(20, 10)",
    "    target_code.add_to_cart(1, 10, 10)",
    "    target_code.add_to_cart(1, 20, 2)",
    "    result = target_code.create_order(1, 0)",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"status\"] == \"confirmed\"",
    "    assert len(result[\"lines\"]) == 2",
    "    line1 = next(l for l in result[\"lines\"] if l[\"product_id\"] == 10)",
    "    assert line1[\"quantity\"] == 5",
    "    assert target_code._INVENTORY[10][\"stock\"] == 0",
    "    line2 = next(l for l in result[\"lines\"] if l[\"product_id\"] == 20)",
    "    assert line2[\"quantity\"] == 2",
    "    assert target_code._INVENTORY[20][\"stock\"] == 8",
    "    assert result[\"subtotal\"] == 900.0",
    "def test_create_order_failure_corrupt_orders_dict_raises(corrupt_orders_dict):",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(1, 10)",
    "    target_code.add_to_cart(1, 1, 5)",
    "    with pytest.raises(AttributeError):",
    "        target_code.create_order(1, 0)",
    "def test_calculate_order_total_normal():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 100)",
    "    target_code.add_to_cart(1, 10, 2)",
    "    order = target_code.create_order(1, 15.0)",
    "    total = target_code.calculate_order_total(order[\"order_id\"])",
    "    assert total == 215.0",
    "def test_calculate_order_total_edge_non_existent_order():",
    "    total = target_code.calculate_order_total(999)",
    "    assert total == 0.0",
    "def test_calculate_order_total_edge_invalid_order_id():",
    "    total = target_code.calculate_order_total(\"invalid\")",
    "    assert total == 0.0",
    "    target_code.reset_demo_state()",
    "    total = target_code.calculate_order_total(-5)",
    "    assert total == 0.0",
    "def test_calculate_order_total_edge_include_tax_ignored():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 100)",
    "    target_code.add_to_cart(1, 10, 2)",
    "    order = target_code.create_order(1, 10.0)",
    "    total_with_tax = target_code.calculate_order_total(order[\"order_id\"], True)",
    "    total_without_tax = target_code.calculate_order_total(order[\"order_id\"], False)",
    "    assert total_with_tax == 210.0",
    "    assert total_without_tax == 210.0",
    "def test_calculate_order_total_failure_corrupt_orders_dict_raises(corrupt_orders_dict):",
    "    with pytest.raises(AttributeError):",
    "        target_code.calculate_order_total(1)",
    "def test_cancel_order_normal():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    order = target_code.create_order(1, 0)",
    "    result = target_code.cancel_order(order[\"order_id\"], \"Customer changed mind\")",
    "    assert result[\"order_id\"] == order[\"order_id\"]",
    "    assert result[\"status\"] == \"cancelled\"",
    "    assert result[\"cancel_reason\"] == \"Customer changed mind\"",
    "    assert target_code._ORDERS[order[\"order_id\"]][\"status\"] == \"cancelled\"",
    "    assert \"cancelled_at\" in target_code._ORDERS[order[\"order_id\"]]",
    "def test_cancel_order_edge_non_existent_order():",
    "    result = target_code.cancel_order(999, \"Not found reason\")",
    "    assert result[\"order_id\"] == 999",
    "    assert result[\"status\"] == \"not_found\"",
    "    assert result[\"reason\"] == \"Not found reason\"",
    "def test_cancel_order_edge_already_cancelled_order():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    order = target_code.create_order(1, 0)",
    "    target_code.cancel_order(order[\"order_id\"], \"First cancel\")",
    "    result = target_code.cancel_order(order[\"order_id\"], \"Second cancel\")",
    "    assert result[\"order_id\"] == order[\"order_id\"]",
    "    assert result[\"status\"] == \"already_cancelled\"",
    "    assert result[\"reason\"] == \"Second cancel\"",
    "def test_cancel_order_edge_invalid_order_id():",
    "    result = target_code.cancel_order(\"invalid_oid\", \"Bad ID\")",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"status\"] == \"not_found\"",
    "    target_code.reset_demo_state()",
    "    result = target_code.cancel_order(-5, \"Negative ID\")",
    "    assert result[\"order_id\"] == 1",
    "    assert result[\"status\"] == \"not_found\"",
    "def test_cancel_order_edge_invalid_reason():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    order = target_code.create_order(1, 0)",
    "    result = target_code.cancel_order(order[\"order_id\"], None)",
    "    assert result[\"cancel_reason\"] == \"customer_request\"",
    "def test_cancel_order_failure_corrupt_orders_dict_raises(corrupt_orders_dict):",
    "    with pytest.raises(AttributeError):",
    "        target_code.cancel_order(1, \"reason\")",
    "def test_get_customer_history_normal_with_orders():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    order1 = target_code.create_order(1, 0)",
    "    target_code.register_customer(2, \"Bob\")",
    "    target_code.upsert_inventory(20, 10)",
    "    target_code.add_to_cart(2, 20, 1)",
    "    target_code.create_order(2, 0)",
    "    target_code.add_to_cart(1, 10, 2)",
    "    order2 = target_code.create_order(1, 0)",
    "    history = target_code.get_customer_history(1)",
    "    assert len(history) == 2",
    "    assert history[0][\"order_id\"] == order1[\"order_id\"]",
    "    assert history[1][\"order_id\"] == order2[\"order_id\"]",
    "    assert all(o[\"customer_id\"] == 1 for o in history)",
    "def test_get_customer_history_normal_no_orders():",
    "    target_code.register_customer(1, \"Alice\")",
    "    history = target_code.get_customer_history(1)",
    "    assert history == []",
    "def test_get_customer_history_edge_non_existent_customer():",
    "    history = target_code.get_customer_history(999)",
    "    assert history == []",
    "def test_get_customer_history_edge_invalid_customer_id():",
    "    history = target_code.get_customer_history(\"invalid_cid\")",
    "    assert history == []",
    "def test_get_customer_history_failure_corrupt_orders_dict_raises(corrupt_orders_dict):",
    "    # Corrupting _ORDERS to make iteration fail",
    "    with pytest.raises(AttributeError):",
    "        target_code.get_customer_history(1)",
    "def test_generate_sales_report_normal_mixed_orders():",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    order1 = target_code.create_order(1, 0)",
    "    target_code.register_customer(2, \"Bob\")",
    "    target_code.upsert_inventory(20, 10)",
    "    target_code.add_to_cart(2, 20, 2)",
    "    order2 = target_code.create_order(2, 0)",
    "    target_code.add_to_cart(1, 10, 2)",
    "    order3 = target_code.create_order(1, 0)",
    "    target_code.cancel_order(order2[\"order_id\"], \"Fraud\")",
    "    report = target_code.generate_sales_report(1, 3)",
    "    assert report[\"order_count\"] == 3",
    "    assert report[\"confirmed_count\"] == 2",
    "    assert report[\"cancelled_count\"] == 1",
    "    assert report[\"gross_revenue\"] == 300.0",
    "    assert isinstance(report[\"last_updated\"], str)",
    "def test_generate_sales_report_edge_no_orders():",
    "    report = target_code.generate_sales_report(1, 10)",
    "    assert report[\"order_count\"] == 0",
    "    assert report[\"confirmed_count\"] == 0",
    "    assert report[\"cancelled_count\"] == 0",
    "    assert report[\"gross_revenue\"] == 0.0",
    "def test_generate_sales_report_edge_start_end_ids_ignored():",
    "    # The current implementation of generate_sales_report ignores start_order_id and end_order_id.",
    "    target_code.register_customer(1, \"Alice\")",
    "    target_code.upsert_inventory(10, 10)",
    "    target_code.add_to_cart(1, 10, 1)",
    "    target_code.create_order(1, 0)",
    "    target_code.upsert_inventory(20, 10)",
    "    target_code.add_to_cart(1, 20, 2)",
    "    target_code.create_order(1, 0)",
    "    report_all = target_code.generate_sales_report(1, 2)",
    "    report_limited = target_code.generate_sales_report(1, 1)",
    "    report_invalid_range = target_code.generate_sales_report(100, 200)",
    "    assert report_all[\"order_count\"] == 2",
    "    assert report_all[\"confirmed_count\"] == 2",
    "    assert report_all[\"gross_revenue\"] == 500.0",
    "    assert report_all == report_limited",
    "    assert report_all == report_invalid_range",
    "def test_generate_sales_report_failure_corrupt_orders_dict_raises(corrupt_orders_dict):",
    "    # Corrupting _ORDERS to make iteration fail",
    "    with pytest.raises(AttributeError):",
    "        target_code.generate_sales_report(1, 5)"
  ],
  "explanation": [
    "Removed malformed string literals at the beginning of the `test_code` array to resolve a `SyntaxError`."
  ]
}
